# Generated by Django 4.2.7 on 2023-12-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_postlike_delete_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
    ]
